services:

  odds-api-producer:
    build:
      context: ./producers
      dockerfile: odds_api_producer/Dockerfile
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kalshi-producer:
    build:
      context: ./producers
      dockerfile: kalshi_producer/Dockerfile
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  game-events-producer:
    build:
      context: ./producers
      dockerfile: game_events_producer/Dockerfile
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  firehose-consumer:
    build:
      context: ./producers
      dockerfile: firehose_consumer/Dockerfile
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=us-east-1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
