version: "3.8"

services:
  odds-api-producer:
    build:
      context: producers/
      dockerfile: odds_api_producer/Dockerfile
    container_name: odds-api-producer
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_PROFILE=sports-betting
    volumes:
      - ~/.aws:/root/.aws:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  kalshi-producer:
    build:
      context: producers/
      dockerfile: kalshi_producer/Dockerfile
    container_name: kalshi-producer
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_PROFILE=sports-betting
    volumes:
      - ~/.aws:/root/.aws:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  game-events-producer:
    build:
      context: producers/
      dockerfile: game_events_producer/Dockerfile
    container_name: game-events-producer
    restart: unless-stopped
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_PROFILE=sports-betting
    volumes:
      - ~/.aws:/root/.aws:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"