export const TEAM_ABBR: Record<string, string> = {
  // NBA
  "Atlanta Hawks": "ATL",
  "Boston Celtics": "BOS",
  "Brooklyn Nets": "BKN",
  "Charlotte Hornets": "CHA",
  "Chicago Bulls": "CHI",
  "Cleveland Cavaliers": "CLE",
  "Dallas Mavericks": "DAL",
  "Denver Nuggets": "DEN",
  "Detroit Pistons": "DET",
  "Golden State Warriors": "GSW",
  "Houston Rockets": "HOU",
  "Indiana Pacers": "IND",
  "LA Clippers": "LAC",
  "Los Angeles Clippers": "LAC",
  "Los Angeles Lakers": "LAL",
  "Memphis Grizzlies": "MEM",
  "Miami Heat": "MIA",
  "Milwaukee Bucks": "MIL",
  "Minnesota Timberwolves": "MIN",
  "New Orleans Pelicans": "NOP",
  "New York Knicks": "NYK",
  "Oklahoma City Thunder": "OKC",
  "Orlando Magic": "ORL",
  "Philadelphia 76ers": "PHI",
  "Phoenix Suns": "PHX",
  "Portland Trail Blazers": "POR",
  "Sacramento Kings": "SAC",
  "San Antonio Spurs": "SAS",
  "Toronto Raptors": "TOR",
  "Utah Jazz": "UTA",
  "Washington Wizards": "WAS",
  // NCAAB
  "Akron Zips": "AKR",
  "Alabama A&M Bulldogs": "AAMU",
  "Alabama Crimson Tide": "ALA",
  "Arizona State Sun Devils": "ASU",
  "Arizona Wildcats": "ARIZ",
  "Arkansas Razorbacks": "ARK",
  "Auburn Tigers": "AUB",
  "BYU Cougars": "BYU",
  "Bradley Braves": "BRAD",
  "California Baptist Lancers": "CBU",
  "California Golden Bears": "CAL",
  "CSU Fullerton Titans": "CSUF",
  "CSU Northridge Matadors": "CSUN",
  "Charlotte 49ers": "CLT",
  "Clemson Tigers": "CLEM",
  "Davidson Wildcats": "DAV",
  "Dayton Flyers": "DAY",
  "Duke Blue Devils": "DUKE",
  "Florida Gators": "FLA",
  "Furman Paladins": "FUR",
  "George Mason Patriots": "GMU",
  "George Washington Colonials": "GWU",
  "Georgia Bulldogs": "UGA",
  "Gonzaga Bulldogs": "GONZ",
  "Hawai'i Rainbow Warriors": "HAW",
  "High Point Panthers": "HP",
  "Hofstra Pride": "HOF",
  "Houston Cougars": "HOU",
  "Howard Bison": "HOW",
  "Idaho Vandals": "IDHO",
  "Illinois Fighting Illini": "ILL",
  "Iowa Hawkeyes": "IOWA",
  "Iowa State Cyclones": "ISU",
  "Jacksonville State Gamecocks": "JOES",
  "Kansas Jayhawks": "KU",
  "Kennesaw State Owls": "KENN",
  "Kent State Golden Flashes": "KENT",
  "Lehigh Mountain Hawks": "LEH",
  "Liberty Flames": "LIB",
  "LIU Sharks": "LIU",
  "Louisville Cardinals": "LOU",
  "Massachusetts Minutemen": "MASS",
  "McNeese Cowboys": "MCNS",
  "Miami (OH) RedHawks": "MOH",
  "Michigan State Spartans": "MSU",
  "Michigan Wolverines": "MICH",
  "Missouri Tigers": "MIZZ",
  "Murray State Racers": "MURR",
  "NC State Wolfpack": "NCST",
  "Navy Midshipmen": "NAVY",
  "Nebraska Cornhuskers": "NEB",
  "Nevada Wolf Pack": "NEV",
  "New Mexico Lobos": "UNM",
  "North Carolina Tar Heels": "UNC",
  "North Dakota State Bison": "NDSU",
  "Northern Iowa Panthers": "UNI",
  "Ohio Bobcats": "OHIO",
  "Ohio State Buckeyes": "OSU",
  "Oklahoma State Cowboys": "OKST",
  "Pennsylvania Quakers": "PENN",
  "Prairie View A&M Panthers": "PV",
  "Purdue Boilermakers": "PUR",
  "Queens University Royals": "QUC",
  "SMU Mustangs": "SMU",
  "Saint Louis Billikens": "SLU",
  "Saint Mary's Gaels": "SMC",
  "Sam Houston Bearkats": "SHSU",
  "Santa Clara Broncos": "SCU",
  "Seattle U Redhawks": "SEA",
  "Siena Saints": "SIE",
  "South Alabama Jaguars": "LSA",
  "South Florida Bulls": "USF",
  "St. John's Red Storm": "SJU",
  "Stephen F. Austin Lumberjacks": "SFA",
  "TCU Horned Frogs": "TCU",
  "Tennessee State Tigers": "TNST",
  "Tennessee Volunteers": "TENN",
  "Texas A&M Aggies": "TXAM",
  "Texas Longhorns": "TEX",
  "Texas Tech Red Raiders": "TTU",
  "Toledo Rockets": "TOL",
  "Troy Trojans": "TROY",
  "UCF Knights": "UCF",
  "UCLA Bruins": "UCLA",
  "UConn Huskies": "CONN",
  "UC Davis Aggies": "UCD",
  "UC Irvine Anteaters": "UCI",
  "UC San Diego Tritons": "UCSD",
  "UMBC Retrievers": "UMBC",
  "UIC Flames": "UIC",
  "UNLV Rebels": "UNLV",
  "Utah State Aggies": "USU",
  "VCU Rams": "VCU",
  "Vanderbilt Commodores": "VAN",
  "Villanova Wildcats": "VILL",
  "Virginia Cavaliers": "UVA",
  "Wake Forest Demon Deacons": "WAKE",
  "Wichita State Shockers": "WICH",
  "Wisconsin Badgers": "WIS",
  "Wright State Raiders": "WRST",
  "Wyoming Cowboys": "WYO",
  "Yale Bulldogs": "YALE",
};

export function abbr(team: string): string {
  return TEAM_ABBR[team] ?? team;
}
